
# auth - public key auth bypasses this stack; pam_permit allows session setup
auth    required      pam_permit.so

# create homedir / repodir on first login
session    required    pam_mkhomedir.so umask=0002
