language: python
python:
  - "3.9"

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DEBUG=True CELERY_TASK_ALWAYS_EAGER=True

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - TEST_MODE=True DEBUG=True CELERY_TASK_ALWAYS_EAGER=True coverage run src/manage.py test src
  - pylama src

after_success:
  - bash <(curl -s https://codecov.io/bash)
