version: '3'
services:
  db:
    image: mariadb:10.5
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file:
      - .env

  app:
    build: .
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:/repos
      - static:/staticfiles
    ports:
      - "8000"
    depends_on:
      - db

  worker:
    build: .
    entrypoint: celery worker -A core -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:/repos:ro
    depends_on:
      - db

  watcher:
    build: .
    entrypoint: /bin/bash -c "/app/manage.py watch_repositories --repo-path=$${REPO_PATH}"
    environment:
      - REPO_PATH=/repos
    env_file:
      - .env
    volumes:
      - borg-repos:/repos:ro
    depends_on:
      - db

  borg:
    build:
      context: .
      dockerfile: Dockerfile.borg
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - borg-repos:/repos
      - borg-config:/config
    ports:
      - "22:22"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static:/staticfiles
    ports:
      - 80:80
    depends_on:
      - app

  redis:
    image: redis:latest

volumes:
  mariadb-data:
  borg-repos:
  borg-config:
  static:
