services:
  db:
    image: mariadb:10.5
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file:
      - .env

  app:
    image: ghcr.io/maltejk/borg-hive:${VERSION:-latest}
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:/repos
      - extrausers-data:/var/lib/extrausers
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    image: ghcr.io/maltejk/borg-hive:${VERSION:-latest}
    command: celery -A core worker -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:/repos:ro
      - extrausers-data:/var/lib/extrausers
    depends_on:
      - db

  watcher:
    image: ghcr.io/maltejk/borg-hive:${VERSION:-latest}
    command: ./manage.py watch_repositories
    env_file:
      - .env
    volumes:
      - borg-repos:/repos:ro
    depends_on:
      - db
    restart: 'on-failure'

  borg:
    image: ghcr.io/maltejk/borg-hive:${VERSION:-latest}-borg
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - borg-repos:/repos
      - borg-config:/config
      - extrausers-data:/var/lib/extrausers:ro
    ports:
      - "${BORG_SSH_PORT}:22"

  redis:
    # image: redis:latest
    image: redis:6.2.19-bookworm

volumes:
  mariadb-data:
  borg-config:
  borg-repos:
  extrausers-data:

#
# EXAMPLES for other repository locations (borg-repos):
#
# BIND MOUNT on docker host:
#
#  volumes:
#    borg-repos:
#      driver_opts:
#        type: none
#        o: bind
#        device: /opt/mydata/path
#
# NFS MOUNT:
#
#   volumes:
#     example:
#       driver_opts:
#         type: "nfs"
#         o: "nfsvers=4,addr=10.40.0.199,nolock,soft,rw"
#         device: ":/docker/example"
#
