version: '3'
services:
  db:
    image: mariadb:10.5
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    env_file:
      - .env

  app:
    image: bpereto/borg-hive:0.1
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:${REPO_PATH}
      - static:/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    image: bpereto/borg-hive:0.1
    entrypoint: celery worker -A core -l INFO -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - borg-config:/config
      - borg-repos:${REPO_PATH}:ro
    depends_on:
      - db

  watcher:
    image: bpereto/borg-hive:0.1
    entrypoint: /bin/bash -c "/app/manage.py watch_repositories --repo-path=$${REPO_PATH}"
    env_file:
      - .env
    volumes:
      - borg-repos:${REPO_PATH}:ro
    depends_on:
      - db

  borg:
    image: bpereto/borg-hive:borg-0.1
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - borg-repos:${REPO_PATH}
      - borg-config:/config
    ports:
      - "${BORG_SSH_PORT}:22"

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   volumes:
  #     - static:/staticfiles
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - app

  ldap:
    # image: osixia/openldap:latest
    image: osixia/openldap:1.4.0-amd64
    env_file:
      - .env
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  redis:
    # image: redis:latest
    image: redis:6.0.7-buster

volumes:
  mariadb-data:
  ldap-data:
  ldap-config:
  borg-repos:
  borg-config:
  static:
