#
# APP
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "borg-hive.fullname" . }}-app
  labels:
    {{- include "borg-hive.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "borg-hive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "borg-hive.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "borg-hive.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:          
            - name: "MYSQL_DATBASE"
              value: "{{ .Values.app.db.name }}"
            - name: "MYSQL_USER"
              value: "{{ .Values.app.db.user }}"
            - name: "MYSQL_HOST"
              value: "{{ .Values.app.db.host }}"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: mariadb
            - name: "DEBUG"
              value: "{{ .Values.app.debug }}"
            - name: "REPO_PATH"
              value: "{{ .Values.app.repoPath }}"
            - name: "APP_LOG_LEVEL"
              value: "{{ .Values.app.logLevel }}"
            - name: "DJANGO_ALLOWED_HOSTS"
              value: "{{ .Values.app.allowedHosts }}"
            - name: "LDAP_HOST"
              value: "ldap://borg-hive-openldap"
            - name: "LDAP_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: LDAP_ADMIN_PASSWORD
                  name: borg-hive-openldap
            - name: "CELERY_BROKER_URL"
              value: "redis://redis-master:6379/0"
            - name: "CELERY_RESULT_BACKEND"
              value: "redis://redis-master:6379/0"
            {{- if .Values.app.email.enabled }}
            - name: "EMAIL_HOST"
              value: "{{ .Values.app.email.host }}"
            - name: "EMAIL_PORT"
              value: "{{ .Values.app.email.port }}"
            - name: "EMAIL_HOST_USER"
              value: "{{ .Values.app.email.host_user }}"
            - name: "EMAIL_HOST_PASSWORD"
              value: "{{ .Values.app.email.host_password }}"
            - name: "EMAIL_USE_SSL"
              value: "{{ .Values.app.email.use_ssl }}"
            - name: "EMAIL_FROM"
              value: "{{ .Values.app.email.from }}"
            {{- end }}
          volumeMounts:
            - mountPath: "/config"
              name: {{ include "borg-hive.fullname" . }}-config
            - mountPath: "/repos"
              name: {{ include "borg-hive.fullname" . }}-repos
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "borg-hive.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-config
        - name: {{ include "borg-hive.fullname" . }}-repos
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-repos
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#
# Borg SSH
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "borg-hive.fullname" . }}-borg
  labels:
    {{- include "borg-hive.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "borg-hive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "borg-hive.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "borg-hive.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.borgtag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:          
            - name: "MYSQL_DATBASE"
              value: "{{ .Values.app.db.name }}"
            - name: "MYSQL_USER"
              value: "{{ .Values.app.db.user }}"
            - name: "MYSQL_HOST"
              value: "{{ .Values.app.db.host }}"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: mariadb
            - name: "DEBUG"
              value: "{{ .Values.app.debug }}"
            - name: "REPO_PATH"
              value: "{{ .Values.app.repoPath }}"
            - name: "APP_LOG_LEVEL"
              value: "{{ .Values.app.logLevel }}"
            - name: "BORG_LDAP_HOST"
              value: "ldap://borg-hive-openldap"
            - name: "BORG_LDAP_BASE_DN"
              value: "dc=borghive,dc=local"
            - name: "BORG_LDAP_READONLY_DN"
              value: "cn=readonly,dc=borghive,dc=local"
            - name: "BORG_LDAP_READONLY_USER_PASSWORD"
              value: "readonly"
          volumeMounts:
            - mountPath: "/config"
              name: {{ include "borg-hive.fullname" . }}-config
            - mountPath: "/repos"
              name: {{ include "borg-hive.fullname" . }}-repos
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 22
          readinessProbe:
            tcpSocket:
              port: 22
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "borg-hive.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-config
        - name: {{ include "borg-hive.fullname" . }}-repos
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-repos
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#
# Borg Watcher
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "borg-hive.fullname" . }}-watcher
  labels:
    {{- include "borg-hive.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "borg-hive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "borg-hive.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "borg-hive.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args: ["/app/manage.py watch_repositories --repo-path=$${REPO_PATH}"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:          
            - name: "MYSQL_DATBASE"
              value: "{{ .Values.app.db.name }}"
            - name: "MYSQL_USER"
              value: "{{ .Values.app.db.user }}"
            - name: "MYSQL_HOST"
              value: "{{ .Values.app.db.host }}"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: mariadb
            - name: "DEBUG"
              value: "{{ .Values.app.debug }}"
            - name: "REPO_PATH"
              value: "{{ .Values.app.repoPath }}"
            - name: "APP_LOG_LEVEL"
              value: "{{ .Values.app.logLevel }}"
            - name: "CELERY_BROKER_URL"
              value: "redis://redis-master:6379/0"
            - name: "CELERY_RESULT_BACKEND"
              value: "redis://redis-master:6379/0"
          volumeMounts:
            - mountPath: "/config"
              name: {{ include "borg-hive.fullname" . }}-config
            - mountPath: "/repos"
              name: {{ include "borg-hive.fullname" . }}-repos
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "borg-hive.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-config
        - name: {{ include "borg-hive.fullname" . }}-repos
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-repos
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#
# Worker
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "borg-hive.fullname" . }}-worker
  labels:
    {{- include "borg-hive.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "borg-hive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "borg-hive.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "borg-hive.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args: ["celery worker -A core -B --scheduler django_celery_beat.schedulers:DatabaseScheduler"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:          
            - name: "MYSQL_DATBASE"
              value: "{{ .Values.app.db.name }}"
            - name: "MYSQL_USER"
              value: "{{ .Values.app.db.user }}"
            - name: "MYSQL_HOST"
              value: "{{ .Values.app.db.host }}"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: mariadb-password
                  name: mariadb
            - name: "DEBUG"
              value: "{{ .Values.app.debug }}"
            - name: "REPO_PATH"
              value: "{{ .Values.app.repoPath }}"
            - name: "APP_LOG_LEVEL"
              value: "{{ .Values.app.logLevel }}"
            - name: "CELERY_BROKER_URL"
              value: "redis://redis-master:6379/0"
            - name: "CELERY_RESULT_BACKEND"
              value: "redis://redis-master:6379/0"
            {{- if .Values.app.email.enabled }}
            - name: "EMAIL_HOST"
              value: "{{ .Values.app.email.host }}"
            - name: "EMAIL_PORT"
              value: "{{ .Values.app.email.port }}"
            - name: "EMAIL_HOST_USER"
              value: "{{ .Values.app.email.host_user }}"
            - name: "EMAIL_HOST_PASSWORD"
              value: "{{ .Values.app.email.host_password }}"
            - name: "EMAIL_USE_SSL"
              value: "{{ .Values.app.email.use_ssl }}"
            - name: "EMAIL_FROM"
              value: "{{ .Values.app.email.from }}"
            {{- end }}
          volumeMounts:
            - mountPath: "/config"
              name: {{ include "borg-hive.fullname" . }}-config
            - mountPath: "/repos"
              name: {{ include "borg-hive.fullname" . }}-repos
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ include "borg-hive.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-config
        - name: {{ include "borg-hive.fullname" . }}-repos
          persistentVolumeClaim:
            claimName: {{ include "borg-hive.fullname" . }}-repos
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
