{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "borg-hive.fullname" . }}-config
  labels:
    {{- include "borg-hive.labels" . | nindent 4 }}
  {{- with .Values.persistence.config.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.persistence.config.finalizers  }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.config.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- if .Values.persistence.config.storageClassName }}
  storageClassName: {{ .Values.persistence.config.storageClassName }}
  {{- end -}}
{{- end -}}
{{- if and .Values.persistence.repos.enabled (not .Values.persistence.repos.existingClaim)}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "borg-hive.fullname" . }}-repos
  labels:
    {{- include "borg-hive.labels" . | nindent 4 }}
  {{- with .Values.persistence.repos.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.persistence.repos.finalizers  }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.repos.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.repos.size | quote }}
  {{- if .Values.persistence.repos.storageClassName }}
  storageClassName: {{ .Values.persistence.repos.storageClassName }}
  {{- end -}}
{{- end -}}