# Generated by Django 4.2.23 on 2025-08-30 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borghive', '0005_alter_alertpreference_id_alter_notification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagerDutyNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='borghive.notification')),
                ('integration_key', models.CharField(max_length=256)),
                ('name', models.CharField(default='Update to set display name', max_length=256)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('borghive.notification',),
        ),
    ]
